name: 'GitHub Actions LZU Auto COVID Health Report'

on:
  workflow_dispatch:  # Allow manual triggers
  schedule:
    # - cron: '0 23 * 1,2,7,8 *' # Schedule on CST 7 everyday during Jan. Feb. Jul. Aug.
    - cron: '0 0 * * *' # Schedule on CST 9 everyday

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
        - name: 'Checkout codes'
          uses: actions/checkout@v2
        - name: 'Set up Python'
          uses: actions/setup-python@v2
          with:
            python-version: '3.9'
        - name: 'Install requirements'
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: 'Auto COVID Health Report'
          env:
            CARDID: ${{ secrets.CARDID }}
            PASSWORD: ${{ secrets.PASSWORD }}
            TZ: Asia/Shanghai
          run: python LZU-Auto-COVID-Health-Report.py >> information.txt && cat information.txt
        - name: 'Error logging and Notifying Using ServerChan or PushPlus'
          env:
            SERVERCHANSCKEY: ${{ secrets.SERVERCHANSCKEY }}
            OPENID: ${{ secrets.OPENID }}
            PPTOKEN: ${{ secrets.PPTOKEN }}
            PPTOPIC: ${{ secrets.PPTOPIC }}
          if: ${{ failure() }}
          run: python Notify-Using-SeverChan-Or-PushPlus.py failure && cat information.txt
        - name: 'Notify Success Using ServerChan or PushPlus'
          env:
            SERVERCHANSCKEY: ${{ secrets.SERVERCHANSCKEY }}
            OPENID: ${{ secrets.OPENID }}
            PPTOKEN: ${{ secrets.PPTOKEN }}
            PPTOPIC: ${{ secrets.PPTOPIC }}
          if: ${{ success() }}
          run: python Notify-Using-SeverChan-Or-PushPlus.py success
